### ISSUE TITLE
prev/next or play/pause buttons

### ISSUE THREAD

**Issue by jojo1243** [marcins/revealjs-simple-gallery#1]
Hey Marcin, 

your gallery is working well once included correctly and kudos for the fullscreen hack.
But how would you include a previous and next button into your gallery for revealjs? Is there an easy way to do this?
cheers

**Comment by marcins** [comment]
It’s pretty neat that something I built 5 years ago is helping someone today, but unfortunately I haven’t used RevealJS in the last 5 years so can’t really help. Maybe there’s an API to do it, or you could look at the reveal source for clues.

Sorry I can’t be more helpful!

**Comment by jojo1243** [comment]
Hello again!
yes it really is! Oh ok, I thought it just needs a tiny bit of code into your gallery.js to maybe just push the next li into 'active' or even just  a pause button to halt the automatic shortly would be sufficient. let me know, if something comes to mind.
thanks again!

**Comment by jojo1243** [comment]
isnt there are variable i can change on.click to force proceeding to the next?
or could you provide explanations to the gallery.step part so i understand to hack my own function in between?
any tips are highly appreciated!
